swagger: "2.0"

info:
  title: "Room API"
  version: "1.0"

basePath: /

schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /rooms/:
    get:
      operationId: api.room.class_instance.list
      description: 'Returns all rooms'
      responses:
        '200':
          description: 'A list of rooms'
          schema:
            type: array
            items:
              $ref: '#/definitions/Room'
    post:
      operationId: api.room.class_instance.post
      description: 'Create a room'
      parameters:
        - in: body
          name: room
          required: true
          schema:
            $ref: '#/definitions/Room'
      responses:
        '201':
          description: 'Room indexed'
          schema:
            $ref: '#/definitions/Room'

  '/rooms/{_id}':
    get:
      operationId: api.room.class_instance.get
      description: 'Get a room'
      parameters:
          - in: path
            name: _id
            required: true
            type: string
      responses:
        '200':
          description: 'Room indexed'
          schema:
            $ref: '#/definitions/Room'

    delete:
      operationId: api.room.class_instance.delete
      description: 'Delete a room'
      parameters:
        - in: path
          name: _id
          required: true
          type: string
      responses:
        '200':
          description: 'Room removed'

definitions:
  ImageUrl:
    type: object
    required:
      - url

    properties:
      url:
        type: string
  Area:
    type: object
    required:
      - name
      - country
      - city
    properties:
      id:
        type: string
      name:
        type: string
      coordinates:
        $ref: '#/definitions/Coordinates'
      country:
        type: string
      city:
        type: string

  Coordinates:
    type: object
    required:
      - lat
      - lon
    properties:
      lat:
        type: number
        format: float
      lon:
        type: number
        format: float

  Room:
    type: object
    required:
      - name
      - description
      - price
      - recurrency
      - url
      - monthly_price
      - property_size
      - provider
      - coordinates
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      price:
        type: integer
      recurrency:
        type: string
      provider:
        type: string
      url:
        type: string
      monthly_price:
        type: integer
      property_size:
        type: string
      area:
        $ref: '#/definitions/Area'
      is_visible:
        type: boolean
      coordinates:
        $ref: '#/definitions/Coordinates'
      images:
        type: array
        $ref: '#/definitions/ImageUrl'